const cars = {
  revuelto: {
    make: "Lamborghini",
    model: "Revuelto",
    price: "£499,950",
    year: "2025",
    mileage: "438 mls",
    heroImage: "./assets/images/2025-lamborghini-revuelto.webp",
    heroImageMobile: "./assets/images/revuelto-mobile.webp",
    description:
      "Finished in striking Rosso Efesto, this Revuelto pairs a thunderous V12‑hybrid heart with electrified immediacy, wrapped in a dramatic carbon‑fibre monofuselage and a cockpit purpose-built for the thrill of driving. Factory‑inspected by Lamborghini‑trained technicians and supplied with the balance of 4 years Lamborghini warranty and 4 years servicing with roadside assistance, it delivers undeniable presence, razor‑sharp dynamics and everyday utility in one irresistible package.",

    highlights: [
      { label: "Mileage", value: "438 mls" },
      { label: "Year", value: "2025" },
      { label: "Price", value: "£499,950" },
    ],

    specs: {
      performance: [
        { label: "0-60 mph", value: "2.5 seconds" },
        { label: "Top Speed", value: "218 mph" },
        { label: "Power", value: "1,015 bhp" },
        { label: "Torque", value: "535 Nm" },
      ],
      drivetrain: [
        { label: "Transmission", value: "Automatic" },
        { label: "Drive Type", value: "4x2" },
        { label: "Drive", value: "4x2" }, // NOTE: "Drive" description appears identical to "Drive Type" — likely needs a full layout description (e.g. "Mid-Rear Engine RWD")
        { label: "Forward Gears", value: "8" },
      ],
      engine: [
        { label: "Stroke", value: "76.4" },
        { label: "Cylinders", value: "12" },
        { label: "Fuel Type", value: "Petrol Parallel PHEV" },
        { label: "Valves Per Cylinder", value: "48" },
        { label: "Aspiration", value: "Injection" },
        { label: "Fuel Delivery", value: "Multi-Point Injection" },
        { label: "Engine Size", value: "6.5 L" },
        { label: "Battery Range", value: "7 Miles" },
      ],
      features: [
        { label: "Exterior Colour", value: "Rosso Efesto" },
        {
          label: "Wheels",
          value: '21" Front / 22" Rear Altanero Forged (Shiny Black)',
        },
        { label: "Brake Calipers", value: "Black CCB" },
        {
          label: "Exterior Details",
          value: "Engine Frame Inserts & Windscreen Frame in Shiny Black",
        },
        { label: "Tailpipes", value: "Matt Black" },
        { label: "Style Package", value: "High Gloss" },
        { label: "Protection", value: "Full PPF" },
        { label: "Interior Finish", value: "Nero Ade" },
        { label: "Interior Materials", value: "Unicolour Leather & Corsa Tex" },
        { label: "Contrast Stitching", value: "Rosso Efesto" },
        { label: "Kickplates", value: "Carbon Matt with Logo & Lighting" },
        { label: "Floor Mats", value: "Leather Piping & Stitching" },
        { label: "Steering Wheel", value: "Full Corsa Tex" },
        { label: "Headrest", value: "Embroidered Lamborghini Shield" },
        { label: "Seat Belts", value: "Rosso Efesto" },
        { label: "Seats", value: "Electric & Heated" },
        { label: "Lighting", value: "Headlamp Package" },
        { label: "Audio", value: "Sonus Faber Premium Sound System" },
        {
          label: "Connectivity",
          value: "Smartphone Interface with Connected Services",
        },
        { label: "Passenger Display", value: "Included" },
        {
          label: "Tracking",
          value: "Lamborghini Connect Vehicle Tracking System",
        },
        { label: "Assistance", value: "Surround Assistance Pack" },
        { label: "Parking", value: "Parking Pack" },
        { label: "Driver Assistance", value: "High Assistant" },
      ],
      configuration: [
        { label: "Body Type", value: "Coupe" },
        { label: "Doors", value: "2" },
        { label: "Seats", value: "2" },
        { label: "Interior Trim", value: "Nero Ade" },
      ],
      other: [
        { label: "Start-Stop", value: "No" },
        { label: "Previous Owners", value: "1" },
        { label: "Reg Date", value: "18/03/2025" },
        { label: "ULEZ Compliant", value: "No" },
      ],
    },

    gallery: [
      {
        src: "./assets/images/revuelto-feature.webp",
        alt: "Front profile",
        isFeatured: true,
      },
      { src: "./assets/images/revuelto-side.webp", alt: "Side profile" },
      { src: "./assets/images/revuelto-rear.webp", alt: "Back profile" },
      { src: "./assets/images/revuelto-wheel.webp", alt: "Wheel detail" },
      { src: "./assets/images/revuelto-interior.webp", alt: "Interior" },
      { src: "./assets/images/revuelto-engine.webp", alt: "Engine" },
      { src: "./assets/images/revuelto-boot.webp", alt: "Boot detail" },
      {
        src: "./assets/images/revuelto-passenger.webp",
        alt: "Passenger-side interior",
      },
      { src: "./assets/images/revuelto-dash.webp", alt: "Dashboard" },
    ],
  },

  "aventador-s": {
    make: "Lamborghini",
    model: "Aventador S Roadster",
    price: "£314,950",
    year: "2018",
    mileage: "8,982 mls",
    heroImage: "./assets/images/2018-lamborghini-aventador-s-roadster.webp",
    heroImageMobile: "./assets/images/aventador-mobile.webp",
    description:
      "Finished in vibrant Arancio Atlas, this Aventador S Roadster represents the absolute pinnacle of open-top, naturally aspirated V12 performance. Combining a thunderous 730 bhp heart with an aggressive aero package and a highly bespoke Bicolore Sportivo leather interior, it is purpose-built for visceral driving thrills. Featuring the Sensonum premium audio system, a transparent engine bonnet, and magneto-rheological suspension with a lifting system, it delivers unmistakable presence and razor-sharp dynamics in one spectacular package.",

    highlights: [
      { label: "Mileage", value: "8,982 mls" },
      { label: "Year", value: "2018" },
      { label: "Price", value: "£314,950" },
    ],

    specs: {
      performance: [
        { label: "0-60 mph", value: "3.0 seconds" },
        { label: "Top Speed", value: "217 mph" },
        { label: "Power", value: "730 bhp" },
        { label: "Torque", value: "690 Nm" },
      ],
      drivetrain: [
        { label: "Transmission", value: "7-Speed ISR" },
        { label: "Drive Type", value: "AWD" },
        { label: "Drive", value: "Mid-Rear Engine AWD" },
        { label: "Forward Gears", value: "7" },
      ],
      engine: [
        { label: "Stroke", value: "76.4" },
        { label: "Cylinders", value: "12" },
        { label: "Fuel Type", value: "Petrol" },
        { label: "Valves Per Cylinder", value: "48" },
        { label: "Aspiration", value: "Naturally Aspirated" },
        { label: "Fuel Delivery", value: "Multi-Point Injection" },
        { label: "Engine Size", value: "6.5 L" },
      ],
      features: [
        { label: "Exterior Colour", value: "Arancio Atlas" },
        { label: "Wheels", value: '20"/21" Dianthus Forged High Gloss Black' },
        { label: "Brake Calipers", value: "Orange" },
        {
          label: "Exterior Details",
          value: "Transparent Engine Bonnet & Shiny Black Accents",
        },
        { label: "Tailpipes", value: "Factory Quad Exhaust" },
        {
          label: "Style Package",
          value: "Style Package & Interior Carbon Fibre Package",
        },
        { label: "Protection", value: "Full PPF" },
        {
          label: "Interior Finish",
          value: "Bicolore Sportivo Leather (S-Trim)",
        },
        { label: "Interior Materials", value: "Nero Ade Leather" },
        { label: "Contrast Stitching", value: "Arancio Leonis" },
        { label: "Kickplates", value: "Factory Branded" },
        { label: "Floor Mats", value: "Factory Matching" },
        { label: "Steering Wheel", value: "Multifunction Perforated Leather" },
        { label: "Headrest", value: "Embroidered Lamborghini Shield" },
        { label: "Seat Belts", value: "Black" },
        { label: "Seats", value: "Electric & Heated Sports Seats" },
        { label: "Lighting", value: "Visibility & Light Package" },
        { label: "Audio", value: "Lamborghini Sensonum System" },
        { label: "Connectivity", value: "DAB & Standard Connectivity" },
        { label: "Passenger Display", value: "Not Equipped" },
        { label: "Tracking", value: "Factory Telematics" },
        { label: "Assistance", value: "Park Assist with Rear View Camera" },
        { label: "Parking", value: "Front & Rear Sensors" },
        {
          label: "Driver Assistance",
          value: "Magneto-Rheological Suspension with Lifting System",
        },
      ],
      configuration: [
        { label: "Body Type", value: "Convertible / Roadster" },
        { label: "Doors", value: "2" },
        { label: "Seats", value: "2" },
        { label: "Interior Trim", value: "Nero Ade / Bicolore Sportivo" },
      ],
      other: [
        { label: "Start-Stop", value: "Yes" },
        { label: "Previous Owners", value: "5" },
        { label: "Reg Date", value: "12/06/2018" },
        { label: "ULEZ Compliant", value: "Yes" },
      ],
    },

    gallery: [
      {
        src: "./assets/images/aventador-feature.webp",
        alt: "Front profile",
        isFeatured: true,
      },
      { src: "./assets/images/aventador-side.webp", alt: "Side profile" },
      { src: "./assets/images/aventador-rear.webp", alt: "Back profile" },
      { src: "./assets/images/aventador-wheel.webp", alt: "Wheel detail" },
      { src: "./assets/images/aventador-interior.webp", alt: "Interior" },
      { src: "./assets/images/aventador-engine.webp", alt: "Engine" },
      { src: "./assets/images/aventador-seats.webp", alt: "Seats" },
      { src: "./assets/images/aventador-boot.webp", alt: "Boot detail" },
      { src: "./assets/images/aventador-dash.webp", alt: "Dashboard" },
    ],
  },

  vanquish: {
    make: "Aston Martin",
    model: "Vanquish",
    price: "£324,950",
    year: "2025",
    mileage: "3,300 mls",
    heroImage: "./assets/images/2025-aston-martin-vanquish.webp",
    heroImageMobile: "./assets/images/vanquish-mobile.webp",
    description:
      "Finished in deep Onyx Black and shielded by full Satin Topaz Paint Protection Film, this 2025 Aston Martin Vanquish represents the absolute pinnacle of British grand touring. Housing a monumental 824 bhp twin-turbocharged V12, it delivers devastating performance wrapped in unparalleled luxury. The bespoke Onyx Black leather interior, accented by red contrast stitching and satin carbon fibre, is complemented by the masterful Bowers & Wilkins audio system and ventilated Sports Plus seats. Offering a blend of visceral power, timeless elegance, and razor-sharp dynamics, it is the ultimate expression of the modern super GT.",

    highlights: [
      { label: "Mileage", value: "3,300 mls" },
      { label: "Year", value: "2025" },
      { label: "Price", value: "£324,950" },
    ],

    specs: {
      performance: [
        { label: "0-60 mph", value: "3.3 seconds" },
        { label: "Top Speed", value: "214 mph" },
        { label: "Power", value: "824 bhp" },
        { label: "Torque", value: "738 Nm" },
      ],
      drivetrain: [
        { label: "Transmission", value: "8-Speed Automatic" },
        { label: "Drive Type", value: "RWD" },
        { label: "Drive", value: "Front Mid-Mounted Engine RWD" },
        { label: "Forward Gears", value: "8" },
      ],
      engine: [
        { label: "Stroke", value: "70.0" },
        { label: "Cylinders", value: "12" },
        { label: "Fuel Type", value: "Petrol" },
        { label: "Valves Per Cylinder", value: "48" },
        { label: "Aspiration", value: "Twin-Turbocharged" },
        { label: "Fuel Delivery", value: "Direct Electronic Injection" },
        { label: "Engine Size", value: "5.2 L" },
      ],
      features: [
        { label: "Exterior Colour", value: "Onyx Black" },
        {
          label: "Wheels",
          value: '21" Multi-Spoke Satin Black Diamond Turned',
        },
        { label: "Brake Calipers", value: "Red (Carbon Ceramic)" },
        {
          label: "Exterior Details",
          value: "Gloss Black Exterior Packs & Bright Exhaust Finisher",
        },
        { label: "Tailpipes", value: "Bright Finish" },
        {
          label: "Style Package",
          value: "Satin Carbon & Satin Dark Chrome Interior Packs",
        },
        { label: "Protection", value: "Full Body Satin Topaz PPF" },
        { label: "Interior Finish", value: "Onyx Black Leather" },
        {
          label: "Interior Materials",
          value: "Leather with Satin Carbon Seat Backs",
        },
        { label: "Contrast Stitching", value: "Red" },
        { label: "Kickplates", value: "Factory Branded" },
        { label: "Floor Mats", value: "Factory Matching" },
        {
          label: "Steering Wheel",
          value: "Sports Leather with Carbon Fibre Paddles",
        },
        { label: "Headrest", value: "Aston Martin Wings Embroidery" },
        { label: "Seat Belts", value: "Black" },
        { label: "Seats", value: "Ventilated & Heated Sports Plus Seats" },
        {
          label: "Lighting",
          value: "Matrix LED Headlamps with Auto High Beam",
        },
        { label: "Audio", value: "Bowers & Wilkins Audio System" },
        { label: "Connectivity", value: "Aston Martin Connectivity Suite" },
        { label: "Passenger Display", value: "Not Equipped" },
        { label: "Tracking", value: "Factory Telematics" },
        { label: "Assistance", value: "Blind Spot Monitoring & 360 Camera" },
        { label: "Parking", value: "360 Camera & Parking Sensors" },
        {
          label: "Driver Assistance",
          value: "Advanced Stability Systems & Driver Modes",
        },
      ],
      configuration: [
        { label: "Body Type", value: "Coupe" },
        { label: "Doors", value: "2" },
        { label: "Seats", value: "2" },
        { label: "Interior Trim", value: "Onyx Black Leather" },
      ],
      other: [
        { label: "Start-Stop", value: "Yes" },
        { label: "Previous Owners", value: "2" },
        { label: "Reg Date", value: "02/06/2025" },
        { label: "ULEZ Compliant", value: "No" },
      ],
    },

    gallery: [
      {
        src: "./assets/images/vanquish-feature.webp",
        alt: "Front profile",
        isFeatured: true,
      },
      { src: "./assets/images/vanquish-side.webp", alt: "Side profile" },
      { src: "./assets/images/vanquish-rear.webp", alt: "Back profile" },
      { src: "./assets/images/vanquish-wheel.webp", alt: "Wheel detail" },
      { src: "./assets/images/vanquish-interior.webp", alt: "Interior" },
      { src: "./assets/images/vanquish-engine.webp", alt: "Engine" },
      { src: "./assets/images/vanquish-seats.webp", alt: "Seats" },
      { src: "./assets/images/vanquish-dash.webp", alt: "Dashboard" },
      { src: "./assets/images/vanquish-steering.webp", alt: "Steering Wheel" },
    ],
  },

  "urus-se": {
    make: "Lamborghini",
    model: "Urus SE",
    price: "£249,950",
    year: "2025",
    mileage: "6,432 mls",
    heroImage: "./assets/images/2025-lamborghini-urus-se.webp",
    heroImageMobile: "./assets/images/urus-se-mobile.webp",
    description:
      "Finished in imposing Nero Helene and fully protected by Satin Topaz Paint Protection Film, the 2025 Urus SE redefines the super-SUV segment. Combining a thunderous 4.0L twin-turbocharged V8 with advanced hybrid electric architecture, it delivers a staggering 666 bhp alongside uncompromised everyday usability. Inside, the cabin is a masterclass in bespoke craftsmanship, featuring Sportivo leather with Arancio Leonis contrast stitching, massaging front seats, and the Big Interior Carbon Package. With the Bang & Olufsen 3D Advanced Sound System and highly dynamic ANIMA driving modes, it offers unparalleled versatility and visceral Lamborghini performance.",

    highlights: [
      { label: "Mileage", value: "6,432 mls" },
      { label: "Year", value: "2025" },
      { label: "Price", value: "£249,950" },
    ],

    specs: {
      performance: [
        { label: "0-60 mph", value: "3.6 seconds" },
        { label: "Top Speed", value: "190 mph" },
        { label: "Power", value: "666 bhp" },
        { label: "Torque", value: "850 Nm" },
      ],
      drivetrain: [
        { label: "Transmission", value: "8-Speed Automatic" },
        { label: "Drive Type", value: "AWD" },
        { label: "Drive", value: "Front-Mounted Engine AWD" },
        { label: "Forward Gears", value: "8" },
      ],
      engine: [
        { label: "Stroke", value: "86.0" },
        { label: "Cylinders", value: "8" },
        { label: "Fuel Type", value: "Petrol Plug-In Hybrid" },
        { label: "Valves Per Cylinder", value: "32" },
        { label: "Aspiration", value: "Twin-Turbocharged" },
        {
          label: "Fuel Delivery",
          value: "Direct Injection & Hybrid Electric Drive",
        },
        { label: "Engine Size", value: "4.0 L" },
      ],
      features: [
        { label: "Exterior Colour", value: "Nero Helene" },
        { label: "Wheels", value: '23" Galanthus Shiny Black' },
        { label: "Brake Calipers", value: "Orange (Carbon Ceramic)" },
        {
          label: "Exterior Details",
          value: "Panoramic Roof & High Gloss Black Badging",
        },
        { label: "Tailpipes", value: "Matt Black Finishers" },
        {
          label: "Style Package",
          value: "High Gloss Black Style & Big Interior Carbon Packs",
        },
        { label: "Protection", value: "Full Body Satin Topaz PPF" },
        { label: "Interior Finish", value: "Nero Helene Sportivo Leather" },
        {
          label: "Interior Materials",
          value: "Ad Personam Trim with Satin Carbon Seat Backs",
        },
        { label: "Contrast Stitching", value: "Arancio Leonis" },
        { label: "Kickplates", value: "Factory Branded" },
        { label: "Floor Mats", value: "Leather Piping & Double Stitching" },
        { label: "Steering Wheel", value: "Leather with Carbon Fibre Paddles" },
        { label: "Headrest", value: "Embroidered Lamborghini Shield" },
        { label: "Seat Belts", value: "Arancio Leonis" },
        {
          label: "Seats",
          value: "Electric, Ventilated, Heated & Massage Front Seats",
        },
        { label: "Lighting", value: "Ambient Light Package" },
        { label: "Audio", value: "Bang & Olufsen 3D Advanced Sound System" },
        { label: "Connectivity", value: "Lamborghini Connect Suite" },
        { label: "Passenger Display", value: "Not Equipped" },
        { label: "Tracking", value: "Lamborghini Connect Vehicle Tracking" },
        {
          label: "Assistance",
          value: "Park Assistance Package & Remote Park Assist",
        },
        { label: "Parking", value: "360° Camera & Remote Park Assist" },
        {
          label: "Driver Assistance",
          value: "ANIMA Drive Modes with Off-Road",
        },
      ],
      configuration: [
        { label: "Body Type", value: "SUV" },
        { label: "Doors", value: "4" },
        { label: "Seats", value: "5" },
        { label: "Interior Trim", value: "Nero Ade / Nero Helene Leather" },
      ],
      other: [
        { label: "Start-Stop", value: "Yes" },
        { label: "Previous Owners", value: "1" },
        { label: "Reg Date", value: "01/03/2025" },
        { label: "ULEZ Compliant", value: "Yes" },
      ],
    },

    gallery: [
      {
        src: "./assets/images/urus-feature.webp",
        alt: "Front profile",
        isFeatured: true,
      },
      { src: "./assets/images/urus-side.webp", alt: "Side profile" },
      { src: "./assets/images/urus-rear.webp", alt: "Back profile" },
      { src: "./assets/images/urus-wheel.webp", alt: "Wheel detail" },
      { src: "./assets/images/urus-interior.webp", alt: "Interior" },
      { src: "./assets/images/urus-seats.webp", alt: "Seats" },
      { src: "./assets/images/urus-dash.webp", alt: "Dashboard" },
      {
        src: "./assets/images/urus-infotainment.webp",
        alt: "Infotainment System",
      },
      { src: "./assets/images/urus-backseats.webp", alt: "Rear Seats" },
    ],
  },

  "continental-gt": {
    make: "Bentley",
    model: "Continental GT Speed First Edition",
    price: "£244,000",
    year: "2025",
    mileage: "1,307 mls",
    heroImage: "./assets/images/2025-bentley-continental-gt.webp",
    heroImageMobile: "./assets/images/continental-gt-mobile.webp",
    description:
      "Finished in sophisticated Granite Grey and boasting the exclusive First Edition Specification, this 2025 Bentley Continental GT Speed marks a new era of electrified grand touring. Its 771 bhp V8 hybrid powertrain offers silent city running and devastating cross-continental pace, perfectly paired with a factory-fitted Akrapovic titanium exhaust system for an evocative soundtrack. The handcrafted Beluga and Linen cabin features the iconic Bentley Rotating Display, Naim audio, and a Dark Tint Engine Turned Aluminium console. With Night Vision, a Head-Up Display, and Mulliner-animated welcome lamps, this First Edition is the ultimate expression of modern British luxury and performance.",

    highlights: [
      { label: "Mileage", value: "1,307 mls" },
      { label: "Year", value: "2025" },
      { label: "Price", value: "£244,000" },
    ],

    specs: {
      performance: [
        { label: "0-60 mph", value: "3.2 seconds" },
        { label: "Top Speed", value: "208 mph" },
        { label: "Power", value: "771 bhp" },
        { label: "Torque", value: "738 Nm" },
      ],
      drivetrain: [
        { label: "Transmission", value: "8-Speed Automatic" },
        { label: "Drive Type", value: "4x4" },
        { label: "Drive", value: "All-Wheel Drive Layout" },
        { label: "Forward Gears", value: "8" },
      ],
      engine: [
        { label: "Stroke", value: "86.0" },
        { label: "Cylinders", value: "8" },
        { label: "Fuel Type", value: "Petrol Plug-In Hybrid" },
        { label: "Valves Per Cylinder", value: "32" },
        { label: "Aspiration", value: "Twin-Turbocharged" },
        { label: "Fuel Delivery", value: "Direct Injection" },
        { label: "Engine Size", value: "4.0 L" },
      ],
      features: [
        { label: "Exterior Colour", value: "Granite Grey" },
        { label: "Wheels", value: '22" Ten Swept Spoke - Black Painted' },
        { label: "Brake Calipers", value: "Black Painted" },
        {
          label: "Exterior Details",
          value: "Blackline Specification & Carbon Fibre Styling Pack",
        },
        { label: "Tailpipes", value: "Akrapovic Exhaust System" },
        {
          label: "Style Package",
          value: "First Edition & Touring Specification",
        },
        { label: "Protection", value: "Extended Range Factory Paint" },
        { label: "Interior Finish", value: "Linen & Beluga Hide" },
        {
          label: "Interior Materials",
          value: "Indented Hide with Dark Tint Engine Turned Aluminium",
        },
        { label: "Contrast Stitching", value: "Mulliner Specification" },
        { label: "Kickplates", value: "First Edition Branded" },
        { label: "Floor Mats", value: "Factory Matching" },
        { label: "Steering Wheel", value: "Heated Single-Tone Indented Hide" },
        { label: "Headrest", value: "Embroidered First Edition Emblems" },
        { label: "Seat Belts", value: "Mulliner Contrast Belts" },
        {
          label: "Seats",
          value: "Front Seat Comfort Specification (Heated/Cooled/Massage)",
        },
        {
          label: "Lighting",
          value: "Mulliner Animated Welcome Lamps & Mood Lighting",
        },
        { label: "Audio", value: "Naim for Bentley Premium Audio" },
        {
          label: "Connectivity",
          value: "Bentley Infotainment with Rotating Display",
        },
        { label: "Passenger Display", value: "Not Equipped" },
        { label: "Tracking", value: "Factory Telematics" },
        { label: "Assistance", value: "Night Vision & HUD" },
        { label: "Parking", value: "360° Camera & Parking Sensors" },
        {
          label: "Driver Assistance",
          value: "Touring Specification Modern Driver Aids",
        },
      ],
      configuration: [
        { label: "Body Type", value: "Coupe" },
        { label: "Doors", value: "2" },
        { label: "Seats", value: "4" },
        { label: "Interior Trim", value: "Beluga / Linen" },
      ],
      other: [
        { label: "Start-Stop", value: "Yes" },
        { label: "Previous Owners", value: "1" },
        { label: "Reg Date", value: "03/11/2025" },
        { label: "ULEZ Compliant", value: "No" },
      ],
    },

    gallery: [
      {
        src: "./assets/images/continental-gt-feature.webp",
        alt: "Front profile",
        isFeatured: true,
      },
      { src: "./assets/images/continental-gt-side.webp", alt: "Side profile" },
      { src: "./assets/images/continental-gt-rear.webp", alt: "Back profile" },
      { src: "./assets/images/continental-gt-wheel.webp", alt: "Wheel detail" },
      { src: "./assets/images/continental-gt-interior.webp", alt: "Interior" },
      { src: "./assets/images/continental-gt-seats.webp", alt: "Seat Detail" },
      { src: "./assets/images/continental-gt-dash.webp", alt: "Dashboard" },
      {
        src: "./assets/images/continental-gt-infotainment.webp",
        alt: "Infotainment System",
      },
      {
        src: "./assets/images/continental-gt-backseats.webp",
        alt: "Rear seats",
      },
    ],
  },

  "huracan-evo": {
    make: "Lamborghini",
    model: "Huracan EVO",
    price: "£174,950",
    year: "2019",
    mileage: "15,002 mls",
    heroImage: "./assets/images/2019-lamborghini-huracan.webp",
    heroImageMobile: "./assets/images/huracan-mobile.webp",
    description:
      "Finished in deep Nero Helene metallic, this 2019 Lamborghini Huracan EVO is the definitive expression of V10 performance. The naturally aspirated 5.2L heart delivers a visceral 631 bhp soundtrack, perfectly managed by the advanced Lamborghini Dinamica Veicolo Integrata (LDVI) system for unparalleled handling. The cabin is a driver-focused sanctuary of Nero Ade Sportivo Alcantara accented by Rosso Alala contrast stitching and carbon fibre trim. Equipped with the Sensonum audio system, transparent engine bonnet, and Aesir forged wheels, this EVO offers a perfect balance of raw emotion and cutting-edge technology.",

    highlights: [
      { label: "Mileage", value: "15,002 mls" },
      { label: "Year", value: "2019" },
      { label: "Price", value: "£174,950" },
    ],

    specs: {
      performance: [
        { label: "0-60 mph", value: "2.9 seconds" },
        { label: "Top Speed", value: "202 mph" },
        { label: "Power", value: "631 bhp" },
        { label: "Torque", value: "600 Nm" },
      ],
      drivetrain: [
        { label: "Transmission", value: "7-Speed Dual-Clutch (LDF)" },
        { label: "Drive Type", value: "AWD" },
        { label: "Drive", value: "Mid-Engine AWD Layout" },
        { label: "Forward Gears", value: "7" },
      ],
      engine: [
        { label: "Stroke", value: "92.8" },
        { label: "Cylinders", value: "10" },
        { label: "Fuel Type", value: "Petrol" },
        { label: "Valves Per Cylinder", value: "40" },
        { label: "Aspiration", value: "Naturally Aspirated" },
        { label: "Fuel Delivery", value: "Direct Electronic Injection" },
        { label: "Engine Size", value: "5.2 L" },
      ],
      features: [
        { label: "Exterior Colour", value: "Nero Helene" },
        { label: "Wheels", value: '20" Aesir Gloss Black' },
        { label: "Brake Calipers", value: "Red (Carbon Ceramic)" },
        {
          label: "Exterior Details",
          value: "EVO Aerodynamics & Transparent Engine Bonnet",
        },
        { label: "Tailpipes", value: "Integrated Central Twin Exhaust" },
        {
          label: "Style Package",
          value: "Body Colour Style Package & EVO Trim",
        },
        { label: "Protection", value: "Paint Protection Film (PPF)" },
        { label: "Interior Finish", value: "Nero Ade" },
        {
          label: "Interior Materials",
          value: "Sportivo Alcantara & Leather with Carbon Fibre",
        },
        { label: "Contrast Stitching", value: "Rosso Alala (Red)" },
        { label: "Kickplates", value: "Branded Lamborghini" },
        { label: "Floor Mats", value: "Factory Matching" },
        {
          label: "Steering Wheel",
          value: "Multifunctional Alcantara with Carbon Fibre",
        },
        { label: "Headrest", value: "Embroidered Lamborghini Shield" },
        { label: "Seat Belts", value: "Black" },
        { label: "Seats", value: "Fully Electric & Heated Sports Seats" },
        { label: "Lighting", value: "Full LED with Y-Shaped DRLs" },
        { label: "Audio", value: "Lamborghini Sensonum System" },
        { label: "Connectivity", value: "DAB, Bluetooth & USB" },
        { label: "Passenger Display", value: "Not Equipped" },
        { label: "Tracking", value: "Factory Telematics Available" },
        { label: "Assistance", value: "LDS Steering & LDVI Dynamics" },
        {
          label: "Parking",
          value: "Front & Rear Sensors with Rear View Camera",
        },
        {
          label: "Driver Assistance",
          value: "ANIMA Drive Mode Selector & Stability Systems",
        },
      ],
      configuration: [
        { label: "Body Type", value: "Coupe" },
        { label: "Doors", value: "2" },
        { label: "Seats", value: "2" },
        { label: "Interior Trim", value: "Nero Ade Sportivo" },
      ],
      other: [
        { label: "Start-Stop", value: "Yes" },
        { label: "Previous Owners", value: "5" },
        { label: "Reg Date", value: "24/07/2019" },
        { label: "ULEZ Compliant", value: "Yes" },
      ],
    },

    gallery: [
      {
        src: "./assets/images/huracan-feature.webp",
        alt: "Front profile",
        isFeatured: true,
      },
      { src: "./assets/images/huracan-side.webp", alt: "Side profile" },
      { src: "./assets/images/huracan-rear.webp", alt: "Back profile" },
      { src: "./assets/images/huracan-wheel.webp", alt: "Wheel detail" },
      { src: "./assets/images/huracan-interior.webp", alt: "Interior" },
      { src: "./assets/images/huracan-engine.webp", alt: "Engine" },
      { src: "./assets/images/huracan-cockpit.webp", alt: "Cockpit view" },
      { src: "./assets/images/huracan-dash.webp", alt: "Dashboard" },
      { src: "./assets/images/huracan-seats.webp", alt: "Seat detail" },
    ],
  },
};
